/***************
 * AUTO-GENERATED BY SHEETS BUILDER
 * Backend: export-backend
 *
 * Modes:
 * - meta
 * - schema
 * - view        (public read)
 * - insert      (write, requires apiKey)
 * - getById     (write-key protected)
 * - update      (write-key protected)
 * - delete      (write-key protected)
 ***************/

// ===== CONFIG =====
const BACKEND_NAME = "export-backend";
const SHEET_NAME = "Export";
const SPREADSHEET_ID = "";
const API_KEY = "CHANGE_ME_WRITE_KEY_2026";
const BUILD_MARKER = "GENERATED_APP_BACKEND_V1";
const BUILD_TIME = new Date().toISOString();

const SHEET_HEADERS = [
  "Data",
  "Conto",
  "Descrizione",
  "Cliente/Fornitore",
  "Entrate",
  "Uscite",
  "Saldo prog.vo"
];
const HEADERS = [
  "data",
  "conto",
  "descrizione",
  "cliente/fornitore",
  "entrate",
  "uscite",
  "saldo prog.vo"
];
const REQUIRED_ON_INSERT = [];
const OPTIONAL_ON_INSERT = [
  "data",
  "conto",
  "descrizione",
  "cliente/fornitore",
  "entrate",
  "uscite",
  "saldo prog.vo"
];
const COMPUTED = [];
const ENUMS = {
  "conto": [
    "Ing Direct NV",
    "BANCOPOSTA"
  ]
};
const CONSTRAINTS = {
  "cliente/fornitore": {
    "maxLen": 255,
    "required": false,
    "type": "string"
  },
  "conto": {
    "required": false,
    "type": "enum"
  },
  "data": {
    "format": "dd/mm/yyyy",
    "required": false,
    "type": "date"
  },
  "descrizione": {
    "maxLen": 255,
    "required": false,
    "type": "string"
  },
  "entrate": {
    "maxLen": 255,
    "required": false,
    "type": "string"
  },
  "saldo prog.vo": {
    "maxLen": 255,
    "required": false,
    "type": "string"
  },
  "uscite": {
    "min": 0,
    "required": false,
    "type": "int"
  }
};

const ENUM_CONTO = [
  "Ing Direct NV",
  "BANCOPOSTA"
];

/***************
 * ENTRY POINT
 ***************/
function doGet(e) {
  const p = (e && e.parameter) ? e.parameter : {};
  const cb = String(p.cb || "").trim();

  if (!cb) return ContentService.createTextOutput("Missing cb (JSONP)");

  try {
    const mode = String(p.mode || "meta").trim();
    const debug = String(p.debug || "") === "1";

    if (mode === "meta")   return jsonp_(cb, meta_());
    if (mode === "schema") return jsonp_(cb, schema_());
    if (mode === "view") {
      const limit = clampInt_(p.limit, 1, 500, 50);
      return jsonp_(cb, view_(limit));
    }

    const apiKey = String(p.apiKey || "");
    if (apiKey !== API_KEY) {
      const out = { ok: false, error: "Invalid apiKey" };
      if (debug) out.debug = { receivedApiKey: apiKey ? "(provided)" : "(missing)" };
      return jsonp_(cb, out);
    }

    if (mode === "insert") return jsonp_(cb, insert_(p, debug));

    if (mode === "getById") {
      const id = clampInt_(p.id, 1, 999999999, 0);
      if (!id) return jsonp_(cb, { ok: false, error: "Missing/invalid id" });
      return jsonp_(cb, getById_(id));
    }

    if (mode === "update") {
      const id = clampInt_(p.id, 1, 999999999, 0);
      if (!id) return jsonp_(cb, { ok: false, error: "Missing/invalid id" });
      return jsonp_(cb, update_(id, p, debug));
    }

    if (mode === "delete") {
      const id = clampInt_(p.id, 1, 999999999, 0);
      if (!id) return jsonp_(cb, { ok: false, error: "Missing/invalid id" });
      return jsonp_(cb, del_(id));
    }

    return jsonp_(cb, { ok: false, error: "Unknown mode", mode });

  } catch (err) {
    return jsonp_(cb, {
      ok: false,
      error: String(err && err.message ? err.message : err)
    });
  }
}

/***************
 * META + SCHEMA
 ***************/
function meta_() {
  return {
    ok: true,
    backend: BACKEND_NAME,
    sheet: SHEET_NAME,
    marker: BUILD_MARKER,
    build: BUILD_TIME,
    publicModes: ["meta", "schema", "view"],
    protectedModes: ["insert", "getById", "update", "delete"]
  };
}

function schema_() {
  return {
    ok: true,
    entity: "Item",
    headers: HEADERS,
    requiredOnInsert: REQUIRED_ON_INSERT,
    optionalOnInsert: OPTIONAL_ON_INSERT,
    computed: COMPUTED,
    enums: ENUMS,
    constraints: CONSTRAINTS
  };
}

/***************
 * VIEW
 ***************/
function view_(limit) {
  const sh = getSheet_();
  ensureHeaders_(sh);

  const lastRow = sh.getLastRow();
  const lastCol = sh.getLastColumn();

  if (lastRow < 2 || lastCol < 1) {
    return { ok: true, headers: HEADERS, rows: [] };
  }

  const numCols = Math.min(lastCol, HEADERS.length);
  const dataRows = lastRow - 1;
  const take = Math.min(limit, dataRows);
  const start = lastRow - take + 1;

  const rows = sh.getRange(start, 1, take, numCols).getValues();
  return { ok: true, headers: HEADERS.slice(0, numCols), rows };
}

/***************
 * INSERT
 ***************/
function insert_(p, debug) {
  const sh = getSheet_();
  ensureHeaders_(sh);

  const data = norm_(p["data"]);
  const conto = norm_(p["conto"]);
  const descrizione = norm_(p["descrizione"]);
  const clientefornitore = norm_(p["cliente/fornitore"]);
  const entrate = norm_(p["entrate"]);
  const uscite = clampInt_(p["uscite"], -999999999, 999999999, 0);
  const saldo_progvo = norm_(p["saldo prog.vo"]);

  const missing = [];
  if (missing.length) return { ok: false, error: "Missing required fields", missing };

  if (conto && ENUM_CONTO.indexOf(conto) === -1) return { ok: false, error: "conto not allowed", allowed: ENUM_CONTO };
  if (descrizione && descrizione.length > 255) return { ok: false, error: "descrizione too long (max 255)" };
  if (clientefornitore && clientefornitore.length > 255) return { ok: false, error: "cliente/fornitore too long (max 255)" };
  if (entrate && entrate.length > 255) return { ok: false, error: "entrate too long (max 255)" };
  if (uscite && uscite < 0) return { ok: false, error: "uscite below min 0" };
  if (saldo_progvo && saldo_progvo.length > 255) return { ok: false, error: "saldo prog.vo too long (max 255)" };

  const id = computeNextId_(sh);
  const rowNumber = sh.getLastRow() + 1;

  sh.getRange(rowNumber, 1, 1, HEADERS.length).setValues([[data,
    conto,
    descrizione,
    clientefornitore,
    entrate,
    uscite,
    saldo_progvo]]);

  const out = { ok: true, id, insertedRow: rowNumber };
  if (debug) out.debug = { keys: Object.keys(p).sort() };
  return out;
}

/***************
 * GET BY ID
 ***************/
function getById_(id) {
  const sh = getSheet_();
  ensureHeaders_(sh);

  const row = findRowById_(sh, id);
  if (!row) return { ok: false, error: "ID not found", id };

  const values = sh.getRange(row, 1, 1, HEADERS.length).getValues()[0];
  const rec = {};
  HEADERS.forEach((h, i) => rec[h] = values[i]);

  return { ok: true, id, record: rec, row };
}

/***************
 * UPDATE
 ***************/
function update_(id, p, debug) {
  const sh = getSheet_();
  ensureHeaders_(sh);

  const row = findRowById_(sh, id);
  if (!row) return { ok: false, error: "ID not found", id };

  const data = norm_(p["data"]);
  const conto = norm_(p["conto"]);
  const descrizione = norm_(p["descrizione"]);
  const clientefornitore = norm_(p["cliente/fornitore"]);
  const entrate = norm_(p["entrate"]);
  const uscite = clampInt_(p["uscite"], -999999999, 999999999, 0);
  const saldo_progvo = norm_(p["saldo prog.vo"]);

  const missing = [];
  if (missing.length) return { ok: false, error: "Missing required fields", missing };

  if (conto && ENUM_CONTO.indexOf(conto) === -1) return { ok: false, error: "conto not allowed", allowed: ENUM_CONTO };
  if (descrizione && descrizione.length > 255) return { ok: false, error: "descrizione too long (max 255)" };
  if (clientefornitore && clientefornitore.length > 255) return { ok: false, error: "cliente/fornitore too long (max 255)" };
  if (entrate && entrate.length > 255) return { ok: false, error: "entrate too long (max 255)" };
  if (uscite && uscite < 0) return { ok: false, error: "uscite below min 0" };
  if (saldo_progvo && saldo_progvo.length > 255) return { ok: false, error: "saldo prog.vo too long (max 255)" };

  sh.getRange(row, 1, 1, HEADERS.length).setValues([[data,
    conto,
    descrizione,
    clientefornitore,
    entrate,
    uscite,
    saldo_progvo]]);

  const out = { ok: true, id, updatedRow: row };
  if (debug) out.debug = { keys: Object.keys(p).sort() };
  return out;
}

/***************
 * DELETE
 ***************/
function del_(id) {
  const sh = getSheet_();
  ensureHeaders_(sh);

  const row = findRowById_(sh, id);
  if (!row) return { ok: false, error: "ID not found", id };

  sh.deleteRow(row);
  return { ok: true, id, deletedRow: row };
}

/***************
 * INTERNALS
 ***************/
function getSheet_() {
  const ss = SPREADSHEET_ID
    ? SpreadsheetApp.openById(SPREADSHEET_ID)
    : SpreadsheetApp.getActiveSpreadsheet();

  const sh = ss.getSheetByName(SHEET_NAME);
  if (!sh) throw new Error("Sheet not found: " + SHEET_NAME);
  return sh;
}

function ensureHeaders_(sh) {
  const lastCol = Math.max(sh.getLastColumn(), SHEET_HEADERS.length);
  const row1 = sh.getRange(1, 1, 1, lastCol).getValues()[0].slice(0, SHEET_HEADERS.length);
  const row1Norm = row1.map(x => String(x || "").trim());

  const ok = SHEET_HEADERS.every((h, i) => row1Norm[i] === h);

  if (!ok) {
    const allEmpty = row1Norm.every(x => !x);
    if (allEmpty && sh.getLastRow() === 0) {
      sh.getRange(1, 1, 1, SHEET_HEADERS.length).setValues([SHEET_HEADERS]);
      return;
    }
    throw new Error("Header mismatch in sheet. Expected: " + SHEET_HEADERS.join(", "));
  }
}

function findRowById_(sh, id) {
  const lastRow = sh.getLastRow();
  if (lastRow < 2) return 0;

  const tf = sh.getRange(2, 1, lastRow - 1, 1)
    .createTextFinder(String(id))
    .matchEntireCell(true);

  const cell = tf.findNext();
  return cell ? cell.getRow() : 0;
}

function computeNextId_(sh) {
  const lastRow = sh.getLastRow();
  if (lastRow < 2) return 1;

  const ids = sh.getRange(2, 1, lastRow - 1, 1).getValues().flat()
    .map(Number)
    .filter(x => !isNaN(x));

  const maxId = ids.length ? Math.max.apply(null, ids) : 0;
  return maxId + 1;
}

function clampInt_(v, min, max, defVal) {
  const n = parseInt(String(v || ""), 10);
  if (isNaN(n)) return defVal;
  return Math.max(min, Math.min(max, n));
}

function norm_(v) {
  return String(v ?? "").trim();
}

function jsonp_(cb, obj) {
  const out = cb + "(" + JSON.stringify(obj) + ");";
  return ContentService
    .createTextOutput(out)
    .setMimeType(ContentService.MimeType.JAVASCRIPT);
}
